version: '3'

services: 
    api:
        image: "mayconcarleterodrigues/falloutshelter"
        ports:
            - 3000:3000
        command: ["npm", "start"]
    
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        depends_on: 
            - api
        ports: 
            - 80:80