version: '3'

services: 
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
    
    mongo-express:
        image: mongo-express
        restart: always
        depends_on: 
            - mongo
        ports:
            - 8081:8081
    
    api:
        image: "mayconcarleterodrigues/falloutshelter"
        environment: 
            - MONGO_URL=mongodb://mongo:27017/api
        depends_on: 
            - mongo
            - mongo-express
        ports:
            - 3000:3000
        command: ["npm", "start"]
        