version: '3'

services: 
    dynamodb-local:
        command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
        image: "amazon/dynamodb-local:latest"
        container_name: dynamodb-local
        working_dir:  /home/dynamodblocal
        ports:
            - "8000:8000"
        volumes:
            - ".:/home/dynamodblocal/data"
        
    dynamodb_manager:
        image: taydy/dynamodb-manager
        privileged: true
        restart: always
        depends_on:
            - dynamodb-local
        ports:
            - "8080:80"
    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
    
    mongo-express:
        image: mongo-express
        restart: always
        depends_on: 
            - mongo
        ports:
            - "8081:8081"