version: '3'

services: 
    mongo:

        image: mongo
        restart: always
        ports:
            - ${MONGO_PORT}:${MONGO_PORT}
    
    mongo-express:
        image: mongo-express
        restart: always
        depends_on: 
            - mongo
        ports:
            - ${MONGO_MANAGER_PORT}:${MONGO_MANAGER_PORT}

    unit-test:
        build:
            context: .
            dockerfile: docker/base-tests.Dockerfile
        volumes:
            - "/app/node_modules"
            - ".:/app"
        depends_on: 
            - mongo
            - mongo-express
        command: ["npm", "run", "test:unit"]

    # run-local:
    #     env_file: 
    #         - .env
    #     build:
    #         context: .
    #         dockerfile: docker/base-tests.Dockerfile
    #     ports:
    #         - ${SERVER_PORT}:${SERVER_PORT}
    #     volumes:
    #         - "/app/node_modules"
    #         - ".:/app"
    #     depends_on: 
    #         - mongo
    #         - mongo-express
    #     command: ["npm", "run", "dev"]
    
    # production:
    #     build:
    #         context: .
    #         dockerfile: docker/build.Dockerfile
    #     ports:
    #         - ${SERVER_PORT}:${SERVER_PORT}
        