version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0


jobs:
  unit-test:
    machine: true
    steps:
      - checkout
      - run:
          name: creating .env
          command: |
            echo "MONGO_URL=${MONGO_URL}" >> .env
            echo "MONGO_PORT=${MONGO_PORT}" >> .env
            echo "MONGO_MANAGER_PORT=${MONGO_MANAGER_PORT}" >> .env
      - run:
          name: printando envs
          command: |
            ls
      - run:
          name: Printando o conteudo
          command: |
            cat .env
      - run:
          name: Unit Tests
          command: | 
            make unit-test  
  deploy-api:
    working_directory: ~/app
    machine: true
    steps:  
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Login docker
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
      - run:
          name: Docker Build
          command: docker build -t mayconcarleterodrigues/falloutshelter -f ~/app/docker/build.Dockerfile .
      - run:
          name: Pushing image to docker hub
          command: docker push mayconcarleterodrigues/falloutshelter
  
  


workflows:
  version: 2
  build_and_tests:
    jobs:
    - unit-test
    - aws-ecr/build-and-push-image:
        requires:
          - unit-test
        account-url: AWS_ECR_ACCOUNT_URL
        aws-access-key-id: AWS_ACCESS_KEY_ID
        aws-secret-access-key: AWS_SECRET_ACCESS_KEY
        context: .
        create-repo: true 
        dockerfile: build.Dockerfile
        no-output-timeout: 20m
        path: ~/app/docker/
        region: AWS_REGION
        repo: falloutShelterRepo
        skip-when-tags-exist: false
        tag: "$CIRCLE_SHA1"
