version: 2.1

jobs:
  unit-test:
    machine: true
    steps:
      - checkout
      - run:
          name: Unit Tests
          command: make unit-test  

workflow:
  tests:
    jobs:
      - unit-test
