version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  eb: circleci/aws-elastic-beanstalk@2.0.0

jobs:
  unit-test:
    machine: true
    steps:
      - checkout
      - run:
          name: creating .env
          command: |
            echo "MONGO_URL=${MONGO_URL}" >> .env
            echo "MONGO_PORT=${MONGO_PORT}" >> .env
            echo "MONGO_MANAGER_PORT=${MONGO_MANAGER_PORT}" >> .env
      - run:
          name: printando envs
          command: |
            ls
      - run:
          name: Printando o conteudo
          command: |
            cat .env
      - run:
          name: Unit Tests
          command: | 
            make unit-test  
  deploy-api-to-docker-hub:
    working_directory: ~/app
    machine: true
    steps:  
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Login docker
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
      - run:
          name: Docker Build
          command: docker build -t mayconcarleterodrigues/falloutshelter -f ~/app/docker/build.Dockerfile .
      - run:
          name: Pushing image to docker hub
          command: docker push mayconcarleterodrigues/falloutshelter
  deploy-api:
    docker:
      - image: mayconcarleterodrigues/falloutshelter
    steps:
      - checkout
      - eb/setup
      - run:
            command: |
                eb create falloutshelter
                eb deploy falloutshelter
                eb status
            name: Deploy Eb

workflows:
  version: 2
  build_and_tests:
    jobs:
      - deploy-api